### ISSUE TITLE
How to extract features from a new video?

### ISSUE THREAD

**Issue by chenxinliu** [qijiezhao/Video-Highlight-Detection#2]
I have trained model in dataset baidu_VH.  I want to see the performance of other videos,  but I don't know the method to extract audio and image features from a new video. Could you like to tell me?
Thank you

**Comment by qijiezhao** [comment]
As for audio, please refer to https://github.com/tensorflow/models/tree/master/research/audioset
As for image, just directly finetuning any pretrained model is OK.
